services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=predictions
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password